/*
Menus are the curated options that users can select to purchase orders from chefs.

--{{ menus }}

*/
CREATE TABLE IF NOT EXISTS api.menus (
  menu_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chef_id INT NOT NULL REFERENCES api.chefs (chef_id) ON DELETE RESTRICT,
  title VARCHAR ( 255 ) NOT NULL,
  description VARCHAR ( 1024 ) NOT NULL
  -- TODO themes
  -- TODO images
);
/* TODO constraints - one menu for free, three for premium, 10 for gold, inf for platinum */

GRANT SELECT ON api.menus TO anon;


CREATE OR REPLACE FUNCTION api.create_menu(session_token_ uuid, title_ VARCHAR, description_ VARCHAR) RETURNS INT AS
$$
DECLARE
  chef_id_ INT;
  menu_id_ INT;
BEGIN
  SELECT api.validate_chef_session(session_token_) INTO chef_id_;
  SELECT api.admin_create_menu(chef_id_, title_, description_) INTO menu_id_;
  RETURN menu_id_;
END;
$$
  LANGUAGE plpgsql
  VOLATILE
  RETURNS NULL ON NULL INPUT;

GRANT EXECUTE ON FUNCTION api.create_menu TO chef;


-- FIXME "system" vs. "admin" verbiage
CREATE OR REPLACE FUNCTION api.admin_create_menu(chef_id_ INT, title_ VARCHAR, description_ VARCHAR) RETURNS INT AS
$$
  INSERT INTO api.menus (chef_id, title, description)
  VALUES (chef_id_, title_, description_)
         RETURNING menu_id;
$$
  LANGUAGE SQL
  VOLATILE
  RETURNS NULL ON NULL INPUT;

GRANT EXECUTE ON FUNCTION api.admin_create_menu TO moderator;
