/*

--{{ users }}

*/
CREATE TABLE IF NOT EXISTS api.users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR ( 255 ) UNIQUE NOT NULL,
  password BYTEA NOT NULL CHECK (octet_length(password) = 64),
  salt BYTEA NOT NULL CHECK (octet_length(salt) = 32),
  created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMPTZ,
  last_active TIMESTAMPTZ,
  deactivated_on TIMESTAMPTZ,
  CONSTRAINT chk_login_created CHECK (created_on <= last_login) -- sanity-check
  /* TODO payment methods */
  /* TODO shipping & billing */
);

-- FIXME use a log of activity & logins

comment on table  api.users is 'All users that can log-in';
comment on column api.users.password is 'Argon2 hashed output';
comment on column api.users.salt is 'Unique salt per-user';
comment on column api.users.deactivated_on is 'Allows a user to pseudo-delete their account without our record-books being corrupted';

-- Deactivate the currently logged-in user identified by their session_token
CREATE OR REPLACE FUNCTION api.session_deactivate_user(session_token_ uuid) RETURNS timestamptz AS
$$
DECLARE
  user_id_ INT;
  deactivated_on_ timestamptz;
BEGIN
  SELECT get_logged_in_user_id(session_token_) INTO user_id_;
  SELECT admin_deactivate_user(user_id_) INTO deactivated_on_;
  RETURN deactivated_on_;
END;
$$
  LANGUAGE plpgsql
  VOLATILE
  RETURNS NULL ON NULL INPUT;

-- Administratively deactivate a user identified by their user_id
CREATE OR REPLACE FUNCTION api.admin_deactivate_user(user_id_ INT) RETURNS timestamptz AS
$$
DECLARE
  deactivated_on_ timestamptz;
BEGIN
  UPDATE api.users SET deactivated_on = CURRENT_TIMESTAMP
    WHERE user_id = user_id_
    RETURNING deactivated_on INTO deactivated_on_;
  DELETE FROM sessions WHERE user_id = user_id_; -- Revoke sessions
  RETURN deactivated_on_;
END;
$$
  LANGUAGE plpgsql
  VOLATILE
  RETURNS NULL ON NULL INPUT;

-- Administratively activate a user by their user_id
CREATE OR REPLACE FUNCTION api.admin_activate_user(user_id_ INT) RETURNS INT AS
$$
  UPDATE api.users SET deactivated_on = NULL
  WHERE user_id = user_id_
  RETURNING user_id;
$$
  LANGUAGE SQL
  VOLATILE
  RETURNS NULL ON NULL INPUT;

-- Filtered user list which only includes active users.
CREATE VIEW api.active_users AS
  SELECT * FROM api.users WHERE deactivated_on IS NULL;
