name:                database-staging
version:             0.1.0.0
github:              "githubuser/database-staging"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/database-staging#readme>

dependencies:
- base >= 4.7 && < 5
- generics-sop
- unliftio-core
- uuid == 1.3.15
- squeal-postgresql == 0.7.0.1
- time

library:
  source-dirs: src

executables:
  database-staging-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - database-staging

tests:
  database-staging-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - database-staging
